\PassOptionsToPackage{unicode=true}{hyperref} % options for packages loaded elsewhere
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provides euro and other symbols
\else % if luatex or xelatex
  \usepackage{unicode-math}
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage[]{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\usepackage{hyperref}
\hypersetup{
            pdftitle={R Notebook},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

% set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother


\title{R Notebook}
\author{}
\date{\vspace{-2.5em}}

\begin{document}
\maketitle

\hypertarget{lets-analyse-divisas-dataset-lets-do-something-interesting-with.}{%
\section{Let's analyse divisas Dataset, let's do something interesting
with.}\label{lets-analyse-divisas-dataset-lets-do-something-interesting-with.}}

i'd like to focus on Mexico, and see whats going on with the peso over
time. Let's get in context, everything is in dollars. Let's do funny
stuff with it

First let's check our Dataset what does it have inside, what colums are
we dealing with As usual we will load everything needed for it, all the
libraries and stuff.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(ggplot2)}
\KeywordTok{library}\NormalTok{(dplyr)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Attaching package: 'dplyr'
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:stats':
## 
##     filter, lag
\end{verbatim}

\begin{verbatim}
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
\end{verbatim}

Now let's load the data, depending wherever you are working in your
system path, you may need to change it, i am inside a working directory
for this project so i have not set R as global, we can set working dir
with the following command

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my_dir <-}\StringTok{ "/home/marck/R_coursera/Pp/"}
\KeywordTok{setwd}\NormalTok{(}\DataTypeTok{dir =}\NormalTok{ my_dir)}
\end{Highlighting}
\end{Shaded}

Therefore now i can have access to the files that are in R\_Courser/Pp.
What happened? we just had set a new variable my\_dir to store the
string path and put it in setwd() function, which, moves our current
workspace to the desired directory.

Now we can load the data.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{divisas <-}\StringTok{ }\KeywordTok{read.csv}\NormalTok{(}\StringTok{"daily_csv.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Depending how you named the data you might need to change the name of
the file into the variable. We just created a new variable named divisas
where we just situated the divisas csv file.

Now, let's check the columns of this csv. There are two ways, the slow
way or the fast way, i mean slow because when you click in the Data
Window in the right( my case) it may load all the data, however it will
display everything in the dataset as DataFrame so you can visualize it.
Spite of that sounding attractive, let's R do it and create a more
secure way, i mean secury because we will also like to know that type of
data we are dealing with.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{str}\NormalTok{(divisas)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    226533 obs. of  3 variables:
##  $ Date   : Factor w/ 12240 levels "1971-01-04","1971-01-05",..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ Country: Factor w/ 22 levels "Australia","Brazil",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ Value  : num  0.899 0.898 0.898 0.898 0.899 ...
\end{verbatim}

Unlike other languages like Python, str() is a function that returns the
structure of the Dataset, this includes, the column names, type of the
data each column has and so on.

It seems there are 3 columns, Date, Country, Value. There are 226533
observations. There are 2 factors, Date with 12240 levels, which means,
there are that number of different values inside and Country with 22
levels, which, means there are in this case 22 Countries.

Let's visualize which countries this dataset includes.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{divisas }\OperatorTok{%>%}\StringTok{ }\KeywordTok{distinct}\NormalTok{(Country)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##           Country
## 1       Australia
## 2          Brazil
## 3          Canada
## 4           China
## 5         Denmark
## 6            Euro
## 7       Hong Kong
## 8           India
## 9           Japan
## 10       Malaysia
## 11         Mexico
## 12    New Zealand
## 13         Norway
## 14      Singapore
## 15   South Africa
## 16    South Korea
## 17         Sweden
## 18    Switzerland
## 19         Taiwan
## 20       Thailand
## 21 United Kingdom
## 22      Venezuela
\end{verbatim}

\end{document}
